// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Jeu0dLD1xlXaq9LJ7ZTZ5UCiJYeesYc',
    appId: '1:607654531180:web:81e79347d5fe87cbca4849',
    messagingSenderId: '607654531180',
    projectId: 'tic-tac-toe-db863',
    authDomain: 'tic-tac-toe-db863.firebaseapp.com',
    storageBucket: 'tic-tac-toe-db863.firebasestorage.app',
    measurementId: 'G-JY6B6VCTR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAHOU-S41lKotuzjP4f8ssFNTLt0FCZfM',
    appId: '1:607654531180:android:8f60891048b307b5ca4849',
    messagingSenderId: '607654531180',
    projectId: 'tic-tac-toe-db863',
    storageBucket: 'tic-tac-toe-db863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbmqCdcwogWRQalmo-JHrq2IijPvzXl34',
    appId: '1:607654531180:ios:c993dab8ad5e67daca4849',
    messagingSenderId: '607654531180',
    projectId: 'tic-tac-toe-db863',
    storageBucket: 'tic-tac-toe-db863.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbmqCdcwogWRQalmo-JHrq2IijPvzXl34',
    appId: '1:607654531180:ios:c993dab8ad5e67daca4849',
    messagingSenderId: '607654531180',
    projectId: 'tic-tac-toe-db863',
    storageBucket: 'tic-tac-toe-db863.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Jeu0dLD1xlXaq9LJ7ZTZ5UCiJYeesYc',
    appId: '1:607654531180:web:54f838c91b601f7bca4849',
    messagingSenderId: '607654531180',
    projectId: 'tic-tac-toe-db863',
    authDomain: 'tic-tac-toe-db863.firebaseapp.com',
    storageBucket: 'tic-tac-toe-db863.firebasestorage.app',
    measurementId: 'G-5F3FLVJRPN',
  );
}
