// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiC0Oe4NzNFfTWhwyn2-f7u0769jCkMKc',
    appId: '1:401635419118:web:3950ea31a0456e58b164ff',
    messagingSenderId: '401635419118',
    projectId: 'tic-tac-toe-app-ec696',
    authDomain: 'tic-tac-toe-app-ec696.firebaseapp.com',
    storageBucket: 'tic-tac-toe-app-ec696.firebasestorage.app',
    measurementId: 'G-P7MGEK4Q7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANzFfy4FTkcgPoQDAsh7EGtMJULTBKjEs',
    appId: '1:401635419118:android:336277400baab95cb164ff',
    messagingSenderId: '401635419118',
    projectId: 'tic-tac-toe-app-ec696',
    storageBucket: 'tic-tac-toe-app-ec696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXNLR7GSLKHwCxGEMPh8L_g4gYBcdPycg',
    appId: '1:401635419118:ios:181427e2c0f33f01b164ff',
    messagingSenderId: '401635419118',
    projectId: 'tic-tac-toe-app-ec696',
    storageBucket: 'tic-tac-toe-app-ec696.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXNLR7GSLKHwCxGEMPh8L_g4gYBcdPycg',
    appId: '1:401635419118:ios:181427e2c0f33f01b164ff',
    messagingSenderId: '401635419118',
    projectId: 'tic-tac-toe-app-ec696',
    storageBucket: 'tic-tac-toe-app-ec696.firebasestorage.app',
    iosBundleId: 'com.example.ttt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiC0Oe4NzNFfTWhwyn2-f7u0769jCkMKc',
    appId: '1:401635419118:web:7394064a854114f2b164ff',
    messagingSenderId: '401635419118',
    projectId: 'tic-tac-toe-app-ec696',
    authDomain: 'tic-tac-toe-app-ec696.firebaseapp.com',
    storageBucket: 'tic-tac-toe-app-ec696.firebasestorage.app',
    measurementId: 'G-1P9B9C7C5C',
  );
}
